//
// Created by meszi on 2017.10.10..
//

#ifndef CPP_2ND_TW_MIGHTY_TEXT_ADVENTURE_INPUTTYPE_H
#define CPP_2ND_TW_MIGHTY_TEXT_ADVENTURE_INPUTTYPE_H

enum InputType {
    INVALID,
    GO_NORTH,
    GO_EAST,
    GO_SOUTH,
    GO_WEST,
    HELP
};

#endif //CPP_2ND_TW_MIGHTY_TEXT_ADVENTURE_INPUTTYPE_H
